version: '3.8'

services:
  web:
    build: ./DatabaseAPI/
    command: python manage.py run -h 0.0.0.0 --port 4000
    volumes:
      - ./DatabaseAPI/:/usr/src/app/
    ports:
      - "6000:5000"
    env_file:
      - ./.env.dev
      - ./DatabaseAPI/.env.dev
    depends_on:
      - db
  user:
    build: ./UserAPI/
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./UserAPI/:/usr/src/user/
    ports:
      - "6758:5000"
    env_file:
      - ./.env.dev
      - ./UserAPI/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  pg-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
volumes:
  db_data: